api:
  title: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"

server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobservice}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

job:
  execution:
    mock-delay-ms: 10000

company:
  service:
    base-url: ${COMPANY_SERVICE_BASE_URL:http://localhost:8080}
    company-list-update-path: /internal/companies/list-update
    company-details-update-path: /internal/companies/details-update
